name: testing java

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -uses: actions/checkout@v2
            -name: Set up JDK 11
             uses: actions/setup-java@v2
             with:
                 java-version: '11'
                 distribution: 'adopt'
            -name: compile and run with javac java
             run: javac ExpressionParser*.java && java ExpressionParserTest 
